project:
  type: website

website:
  favicon: "logo.png"
  sidebar:
    style: "docked"
    title: "winter_arc"
    navbar:
      left:
        - href: index.qmd
          text: Home
        - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


editor: visual

