---
title: "Standing Friday Sandbag Workout Status"
subtitle: "Are we doing this thing?"
format:
  lumo-html: 
    code-fold: false
    logo: "logo.png"                                     # Optional. Path to a logo displayed above the title
    github-repo: "https://github.com/bradlindblad/winter_arc"        # Optional. Adds a github corner at the top right
    primary-color: "#69b3a2"
    self-contained: true
    is-particlejs-enabled: true                          # Optional: display interactive particles in the document header
    bg-image: ""                                         # Optional: link to an image for the header background
author: Team Rampage
date: last-modified
---

```{r}
#| include: false

# Source functions and get weather data, then clean
source("functions.R")

forecast <- possibly_insistently_get_weather()

all <- clean_hourly_weather(forecast)
fri <- all[['Fri']]
full <- all[['Full']]

# Get wind chill and make decisions
chill <- fri |> 
  dplyr::pull(chill)

decision <- go_nogo(chill)
reason <- decide(chill)
```

```{r}
#| echo: false
decision_df <- dplyr::tibble(Category = c("Decision", "Reason"), Value = c(decision, reason))


gt <- fri |> 
  dplyr::select(Chill = chill, Temp = temperature, Wind = windSpeed, Direction = windDirection, Summary = shortForecast, Time = time) |> 
  dplyr::mutate(dplyr::across(everything(), as.character)) |> 
  
  tidyr::pivot_longer(cols = everything(), names_to = 'Category', values_to = 'Value') |> 
    dplyr::bind_rows(decision_df) |> 
  make_gt()
  
```

```{r}
#| echo: false

library(echarts4r)

echart <- full |> 
  dplyr::select(time, chill) |> 
  echarts4r::e_chart(time) |> 
  echarts4r::e_line(chill) |> 
  echarts4r::e_tooltip(trigger = "axis")

```


```{r}
#| echo: false
gt
```

```{r}
#| echo: false
echart
```



